service: gettogether

plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-plugin-tracing

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultStage}
  logs:
    restApi: true
  tracing: true
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource: '*'

custom:
  defaultRegion: eu-west-1
  defaultStage: dev${env:SLSUSER, ""}
  getTogethersTableName: ${self:provider.stage}-gettogethers
  getTogetherSnsTopicName: ${self:provider.stage}-joingettogethers
  testVar: ${ssm:/gettogethers/tableName}
  testVar2: ${ssm:/gettogethers/secureTableName~true}
  notifyOrganiserDLQSnsTopicName: ${self:provider.stage}-joingettogetherdlq
  notifyOrganiserDLQSnsTopic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.notifyOrganiserDLQSnsTopicName}
  
functions:
  getGetTogethers:
    handler: src/functions/getGetTogether.handler
    events:
      - http:
          path: api/getTogethers
          method: get
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/${self:custom.getTogethersTableName}

  sqsFunction:
    handler: src/functions/sqsFunction.handler
    onError: ${self:custom.notifyOrganiserDLQSnsTopic}
    events:
      - sns: ${self:custom.getTogetherSnsTopicName}
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action: ssm:GetParameters*
        Resource: arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/gettogethers/secureTableName
      - Effect: Allow
        Action: sns:Publish
        Resource: ${self:custom.notifyOrganiserDLQSnsTopic}
    environment:
      getTogethersTableNamePath: /gettogethers/secureTableName

  error:
    handler: src/functions/error.handler
    events:
      - sns: ${self:custom.notifyOrganiserDLQSnsTopic}

  joingGetTogether:
    handler: src/functions/joingGetTogether.handler
    events:
      - http:
          path: api/joingGetTogether
          method: post
    iamRoleStatementsInherit: true
    iamRoleStatements: 
      - Effect: Allow
        Action: sns:Publish
        Resource: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.getTogetherSnsTopicName}
    environment:
      getTogethersTopic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:${self:custom.getTogetherSnsTopicName}
      testVar: ${self:custom.testVar}
      testVar2: ${self:custom.testVar2}

    

resources:
  Resources:
    GetTogethersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.getTogethersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    DLQueue:
      Type: AWS::SNS::Topic
      Properties: 
        TopicName: ${self:custom.notifyOrganiserDLQSnsTopicName}
