service: gettogether

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: dev

plugins:
- serverless-pseudo-parameters
- serverless-iam-roles-per-function

functions:
  helloWorld:
    handler: src/functions/getGetTogether.handler
    events:
      - http:
          path: api/getTogethers
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/gettogethers

resources:
  Resources:
    GetTogethersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: gettogethers
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
